config/routes.rb
Rails.application.routes.draw do

  root to: 'pictures#index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions
  resources :favorites, only:[:create, :destroy]
  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  
  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 10}
  validates :password, presence: true
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  
  has_secure_password
  before_validation { email.downcase! }
  
  has_many :pictures
  has_one :profile
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:new, :edit, :show, :destroy]
  before_action :prevention, only: [:edit, :destroy]
  
  def index
    @picture = Picture.order(id: :desc).all
  end
  
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end
  
  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      ContactMailer.picture_mail(current_user).deliver
      redirect_to pictures_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @picture.update(picture_params)
      redirect_to pictures_path
    else
      render 'edit'
    end
  end
  
  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end
  
  def destroy
    @picture.destroy
    redirect_to pictures_path
  end
  
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end
  
  private
  
  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache, :user_id)
  end
  
  def set_picture
    @picture = Picture.find(params[:id])
  end
  
  def prevention
    set_picture
    unless @picture.user_id == current_user.id
      redirect_to pictures_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :prevention, only: [:edit]
  before_action :set_profile, only: [:edit, :update]
  
  def show
    redirect_to user_path
  end
  
  def edit
  end
  
  def update
    if @profile.update(profile_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end
  
  private
  
  def profile_params
    params.require(:profile).permit(:image, :image_cache)
  end
  
  def set_profile
    @profile = User.find(current_user.id).profile
  end
  
  def prevention
    set_profile
    unless @profile.user_id == current_user.id
      redirect_to user_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path
    else
      flash.now[:danger] = 'login failed'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'logout success'
    redirect_to pictures_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save

      @profile = Profile.create!(user_id: @user.id)
      @profile.image = Rails.root.join('app', 'assets', 'images', 'profile_default.jpg').open
      @profile.save!
      
      redirect_to new_session_path
    else
      render 'new'
    end
  end
  
  def destroy
  end
  
  def show
    @profile = User.find(current_user.id).profile
    @favorite_pictures = @user.favorite_pictures
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def profile_params
    params.require(:profile).permit(:image, :image_cache)
  end
  
  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
  
  def login_check
    if !current_user.present?
      redirect_to new_session_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inhosigram</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      
      <div class="top">
        <%= link_to image_tag("inhosigram.PNG"), root_path, class: "top_logo" %>
        <div class="top_user">
          <% if logged_in? %>
            <%= link_to 'new', new_picture_path %>
            <%= link_to "Profile", user_path(current_user.id) %>
            <%= link_to "Logout", session_path(current_user.id), method: :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Login", new_session_path %>
          <% end %>
        </div>
      </div>
      
    
      <div class="main row">
        <%= yield %>
      </div>
    
    </div>
    
    
    
   

    
  </body>
</html>

app/views/pictures/_form.html.erb
<script type="text/javascript" src="/assets/preview.js"></script>
<div class="form">
  <%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  
    
    <label for="image_upload" class="preview"> 
      <div class="label_text">Choose File</div>
      <div class="preview_image"><%= image_tag @picture.image.url if @picture.image.url %></div>
      
      <span class="upload_image"><%= form.file_field :image, id: 'image_upload' %></span> 
    </label>
    

    
    <div class="form-group">
       <%= form.label :content %>
       <%= form.text_field :content, class: 'form-control' %>
    </div>
    
    <%= form.hidden_field :image_cache %>
    
    
    <%= form.submit class: 'button form_submit' %>
  
    
  <% end %>

  <div class="form_back"><%= link_to 'back', pictures_path, class: 'button'%></div>

</div>

app/views/pictures/confirm.html.erb
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  
  <div class="picture">
    <div class="picture_image"><%= image_tag @picture.image.url if @picture.image.url %></div>
    <div class="picture_bottom">
      <div class="picture_bottom_user"><%= @picture.user.name %></div>
      <div class="picture_content"><%= @picture.content %></div>
    </div>
  </div>
  <%= form.submit "submit", class: 'button confirm_submit' %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit 'back', name: 'back', class: 'button confirm_back' %>
<% end %>

app/views/pictures/edit.html.erb
<%= render 'form' %>

app/views/pictures/index.html.erb
<% @picture.each do |picture| %>
<div class="col-xs-12 col-md-6">
  <div class="picture">
    <div class="picture_user">
      <%= image_tag picture.user.profile.image.url if picture.user.profile.image.url %>
      <%= picture.user.name %>
    </div>
    
    <div class="picture_image"><%= image_tag picture.image.url if picture.image.url %></div>
    
    <div class="picture_bottom">
      <div class="picture_option">
        <%= link_to 'show', picture_path(picture.id) %>
      
        <% if defined?(current_user.id) %>
          <% if picture.user_id == current_user.id %>
            <%= link_to 'edit', edit_picture_path(picture.id) %>
            <%= link_to 'delete', picture_path(picture.id), method: :delete %>
          <% end %>
        <% end %>
      </div>
      
      <div class="picture_bottom_user"><%= picture.user.name %></div>
      <div class="picture_content"><%= picture.content %></div>
      
      
    </div>
  </div>
  </div>
<% end %>  

app/views/pictures/new.html.erb
<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="picture">
  <div class="picture_user">
    <%= image_tag current_user.profile.image.url if defined?(current_user.id) && current_user.profile.image.url %>
    <%= @picture.user.name %>
  </div>
  
  <div class="picture_image"><%= image_tag @picture.image.url if @picture.image.url %></div>
  
  <div class="picture_bottom">
    
    <div class="picture_option">
      <% unless @picture.user_id == current_user.id %>
        <% if @favorite.present? %>
          <%= link_to image_tag('/assets/favorite_on.PNG'), favorite_path(id: @favorite.id), method: :delete %>
        <% else %>
          <%= link_to image_tag('/assets/favorite_off.PNG'), favorites_path(picture_id: @picture.id), method: :post %>
        <% end %>
      <% end %>
    </div>
    
    <div class="picture_bottom_user"><%= @picture.user.name %></div>
    <div class="picture_content"><%= @picture.content %></div>
      
  </div>
</div>
 <!--link_to 'back', pictures_path, class: 'button' -->

app/views/profiles/edit.html.erb
<script type="text/javascript" src="/assets/preview.js"></script>
<div class="form">
<%= form_with(model: @profile, local: true, url: profile_path) do |form| %>
  <div class="image_box">
  

    <label for="image_upload" class="preview_profile"> 
      <div class="label_text">Choose File</div>
      <div class="preview_image"><%= image_tag @profile.image.url if @profile.image.url %></div>
      <span class="upload_image"><%= form.file_field :image, id: 'image_upload' %></span> 
    </label>
  </div>
  <%= form.hidden_field :image_cache %>
  
  <%= form.submit class: 'button' %>
  
<% end %>

<%= link_to 'back', user_path, class: 'button' %>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>  
  <div class="sign_up">
    <div class="form-group">
       <%= f.label :name %>
       <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
       <%= f.label :email %>
       <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
       <%= f.label :password %>
       <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
       <%= f.label :password_confirmation %>
       <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit "Create my account", class: 'button' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile">
  <div class="profile_image"><%= image_tag @profile.image.url if @profile.image.url%></div>
  <span class="profile_user"><%= @user.name %></span>
  
  <span class="profile_edit">
    <% if defined?(current_user.id) %>
      <% if @profile.user_id == current_user.id %>
        <%= link_to 'Profile Edit', edit_profile_path(@profile.id), class: 'button' %>
      <% end %>
    <% end %>
  </span>
  
  <div class="profile_email"><%= @user.email %></div>
</div>

<div class="line">Favorite pictures</div>
  
<% @favorite_pictures.each do |favorites_pictures| %>
  <div class="picture">
    <div class="picture_user">
      <%= image_tag favorites_pictures.user.profile.image.url if favorites_pictures.user.profile.image.url%>
      <%= favorites_pictures.user.name %>
    </div>
    
    <div class="picture_image"><%= image_tag favorites_pictures.image.url if favorites_pictures.image.url%></div>
    
    <div class="picture_bottom">
      <div class="picture_option"><%= link_to 'show', picture_path(favorites_pictures.id) %></div>
      
      <div class="picture_bottom_user"><%= favorites_pictures.user.name %></div>
      <div class="picture_content"><%= favorites_pictures.content %></div>
        
    </div>
  </div>
<% end %>